language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t oxhe2038/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true oxhe2038/react-test-app npm run test

after_success:
  - docker build -t oxhe2038/docker-frontend ./frontend
  - docker build -t oxhe2038/docker-backend ./backend
  - docker build -t oxhe2038/docker-nginx ./nginx
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push oxhe2038/docker-frontend
  - docker push oxhe2038/docker-backend
  - docker push oxhe2038/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "Dockerfullstackapp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-376792266454
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY